Recommendatation system are of two type:
    
    > Content based   ---> youtube recommendation based, 
    
    > User/item based   ---> bread +butter

# similarity score

cosine similarity lies between -1 to 1 

In [1]:
# Step1 ---> creating data on small scale first

s1="I learn java"
s2="I learn python"
s3="Virth kohali is a crikerter"
corpus=[s1,s2,s3]

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
#Step 2 ---> filtering data means converting data into corpus into small letters and removing stop words
tf=TfidfVectorizer(lowercase=True,stop_words='english')

In [4]:
# Step 3 ---> sparse_matrix to dense_matrix conversion
sparse_matix=tf.fit_transform(corpus)
dense_matrix=sparse_matix.toarray()

In [5]:
# Step 4 ---> cosine_similarity help us to get the distance between vectors using math's cos angle, where cos 90 means 0 mean not match between 2 vector and cos0 means 1 
# which mean it match 100%  to each other.
# In cosine_similarity, cos degree value lies between -1 to +1 where -1 is absolutly oppositive and +1 means absolutly same.
# Note: cosine similarity show similarity when degree is bigger

from sklearn.metrics.pairwise import cosine_similarity
cs=cosine_similarity(dense_matrix)

In [6]:
# Step 5 ---> cosine_distance help to find the distance between two vector or more. If the distance is higher that means not match between two vectors. if distance is
            # lower that means both vectors are same.
# Note: cosine distance show similarity when distance is smaller

from sklearn.metrics.pairwise import cosine_distances
cd=cosine_distances(dense_matrix)

In [1]:
# step 6 --> importing pandas to read dataset of a movie and clean it.

import pandas as pd
df=pd.read_csv("movies.csv")

In [8]:
# step 7 ---> filterning columns which is required 
df1=df[['name','rating','description']]

In [9]:
# step 8 ---> checking null value in the datasets
df1.isnull().sum()


name              0
rating            0
description    1098
dtype: int64

In [10]:
df1.description.dropna(inplace=True)

C:\Users\786nn\AppData\Local\Temp\ipykernel_21040\4136920275.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.description.dropna(inplace=True)


In [11]:
df1.dropna(inplace=True)

C:\Users\786nn\AppData\Local\Temp\ipykernel_21040\3614008390.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.dropna(inplace=True)


In [12]:
df1

name  rating  \
0                           Neerja     7.9   
1                      Udta Punjab     7.9   
2      Kabhi Khushi Kabhie Gham...     7.5   
3                    Kal Ho Naa Ho     8.0   
4                          Parched     7.6   
...                            ...     ...   
2838                    Run Antony     7.7   
2841                    Jolly Days     7.7   
2842  The Great Story of Sodabuddi     7.7   
2844                        Vamshi     7.7   
2847                  Chaddi Dosth     7.7   

                                            description  
0     Neerja is the story of the courageous Neerja B...  
1     A story that revolves around drug abuse in the...  
2     Yashvardhan Raichand lives a very wealthy life...  
3     Naina, an introverted, perpetually depressed g...  
4     'Parched' is a story about women set in the he...  
...                                                 ...  
2838  Antony is depressed and wants to commit suicid...  
2841  A bubbly tale, the story is about four pairs o...  
2842  The film tells the story of Sodabuddi, who spe...  
2844  Vamshi, under the eye of his mother is living ...  
2847  The plot is simple. Ranganna (Rangayana Raghu)...  

[1752 rows x 3 columns]

In [13]:
# Step 9--->conversion of desciption of movies of dataframe into a corpus using pandas df1.description
# Step 10---> TfidfVectorizer and countVectorizer both use for creating feature from corpus and also contain corpus preprocessing tools like lowercase=True,stop_word='english'
# Step 11---> Creating dense matrix from sparse matix with the help to toarray() method

from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(lowercase=True,stop_words='english')
X_dense=tf.fit_transform(df1.description).toarray()

In [14]:
# Step 12 ---> importing algorithm for recommondation which is NearestNeighbors it partially work like KNN(KNN doesnot have cosinesimilarity in it) and NearestNeighbors have
            # cosine_distance and cosine_similarity 
# Most import NearestNeighbors is for "Unsupervise learning" where "Target" is not required 

from sklearn.neighbors import NearestNeighbors
model1=NearestNeighbors()                                                   # bydefault it calculate equilidian distance
model1.fit(X_dense)

NearestNeighbors()

In [15]:
model1.kneighbors([X_dense[1]],n_neighbors=4)

(array([[0.        , 1.31854472, 1.32062728, 1.32260465]]),
 array([[  1, 848, 861, 361]], dtype=int64))

In [16]:
cosine_dis,pos=model1.kneighbors([X_dense[1]],n_neighbors=4)

In [17]:

model1=NearestNeighbors(metric='cosine')   # internally compute cosine distance (1-cosθ) # if i will not mention (metric='cosine') then it will 
                                            # calculate equilidian distance bydefault which is not much suitable for it 
model1.fit(X_dense)
model1.kneighbors([X_dense[1]],n_neighbors=4) # dense_matrix must pass in 2D array beacuse model train on 2D matrix



(array([[0.        , 0.86928008, 0.8720282 , 0.87464153]]),
 array([[  1, 848, 861, 361]], dtype=int64))

In [18]:
# Step 13 ---> converting dataframe movies name in smaller case so when user inter the data we can match it with dataframe to check the availability of that film

df1.name

def lower(doc):
    corpus_name=[]
    for i in doc:
        corpus_name.append(i.lower())
    return corpus_name

X=lower(df1.name)
df1.name=X
df1

C:\Users\786nn\AppData\Local\Temp\ipykernel_21040\2580008005.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.name=X


name  rating  \
0                           neerja     7.9   
1                      udta punjab     7.9   
2      kabhi khushi kabhie gham...     7.5   
3                    kal ho naa ho     8.0   
4                          parched     7.6   
...                            ...     ...   
2838                    run antony     7.7   
2841                    jolly days     7.7   
2842  the great story of sodabuddi     7.7   
2844                        vamshi     7.7   
2847                  chaddi dosth     7.7   

                                            description  
0     Neerja is the story of the courageous Neerja B...  
1     A story that revolves around drug abuse in the...  
2     Yashvardhan Raichand lives a very wealthy life...  
3     Naina, an introverted, perpetually depressed g...  
4     'Parched' is a story about women set in the he...  
...                                                 ...  
2838  Antony is depressed and wants to commit suicid...  
2841  A bubbly tale, the story is about four pairs o...  
2842  The film tells the story of Sodabuddi, who spe...  
2844  Vamshi, under the eye of his mother is living ...  
2847  The plot is simple. Ranganna (Rangayana Raghu)...  

[1752 rows x 3 columns]

In [19]:
# Step 14 ---> Asking user to search any movie and my program will suggest whether there is any movies in dataframe matching to user seach. if yes then my program will suggest.

movie=input("Enter movies name:")
for i in df1.name:
    if movie==i:
        print('Movies in available')
        

Enter movies name: Neerja


In [20]:
# Finally mergin all the steps to get full flaged recommendation system(content based recommendation)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

tf2=TfidfVectorizer(lowercase=True,stop_words='english')
X_dense=tf2.fit_transform(df1.description).toarray()

model2=NearestNeighbors(metric='cosine')

model2.fit(X_dense)

def lower(doc):
    corpus_name=[]
    for i in doc:
        corpus_name.append(i.lower())
    return corpus_name

X=lower(df1.name)
df1.name=X

movie=input("Enter movies name:").casefold()
for i in df1.name:
    if movie==i:
        cosine_dis,df_pos=model2.kneighbors(tf2.transform([movie]))
        # print(cosine_dis,df_pos)
        for i in df_pos[0][1:5]:
            print(df1.iloc[i].loc['name'])
else:
    print(f"{movie} is not available")

C:\Users\786nn\AppData\Local\Temp\ipykernel_21040\426885423.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.name=X


Enter movies name: Neerja


khwada
sakharam binder
sail
half ticket
neerja is not available
